#Introduction to R Language

## Data structures

### Vectors(collection of same data type)

In [ ]:
X = c(1, 3, 5, 9, 8)
print(X)

[1] 1 3 5 9 8


### List (collection of different data type)

In [ ]:
empId = c(1, 2, 3, 4)
empName = c("Debi", "Sandeep", "Subham", "Shiba")
empList = list(empId, empName)
print(empList)

[[1]]
[1] 1 2 3 4

[[2]]
[1] "Debi"    "Sandeep" "Subham"  "Shiba"  



### Dataframe (table of different data type)

In [ ]:
Name = c("Amiya", "Raj", "Asish")
Language = c("R", "Python", "Java")
Age = c(22, 25, 45)
df = data.frame(Name, Language, Age)
print(df)

   Name Language Age
1 Amiya        R  22
2   Raj   Python  25
3 Asish     Java  45


### Matrix (table of same data type)

In [ ]:
matrix(1:6, nrow = 2, ncol = 3)

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

### Array

In [ ]:
A = array(
  c(1, 2, 3, 4, 5, 6, 7, 8),
  dim = c(2, 2, 2)
)
print(A)

, , 1

     [,1] [,2]
[1,]    1    3
[2,]    2    4

, , 2

     [,1] [,2]
[1,]    5    7
[2,]    6    8



## Variable Assignment

In [ ]:
var1 <- 'simple'
3.5 -> var2
var3 = 6

In [ ]:
# ls function:  built-in function is used to know all the present variables in the workspace.
print(ls())

 [1] "A"        "Age"      "df"       "empId"    "empList"  "empName" 
 [7] "Language" "Name"     "var1"     "var2"     "var3"     "X"       


In [ ]:
# rm () function: a built-in function used to delete an unwanted variable within your workspace.
rm(var3)
print(var3)

ERROR: Error: object 'var3' not found


## Taking inputs from user

In [ ]:
var1 = readline(prompt = 'Enter any number :' )
var1 = readline('Enter any number :' )

Enter any number :1
Enter any number :2


## Printing

### Print Outputs

In [ ]:
x <- "number1"
print (x)
#or
x

[1] "number1"


[1] "number1"

### Print string with variable

In [ ]:
# "\n" for new line
x = 5
cat(x, "is integer\n","new line")

5 is integer
 new line

### Calling the print() function using digits parameter

In [ ]:
x <- 55555 / 7
x
print(x, digits = 2)
print(x, digits = 3)
print(x, digits = 4)

[1] 7936.429

[1] 7936
[1] 7936
[1] 7936


## Conditions

### If- else condition

In [ ]:
a <- 76
b <- 67
if (a > b)
{
  c <- a - b
  print("condition a > b is TRUE")
  print(paste("Difference between a, b is : ", c))
} else
{
  c <- a - b
  print("condition a < b is TRUE")
  print(paste("Difference between a, b is : ", c))
}

[1] "condition a > b is TRUE"
[1] "Difference between a, b is :  9"


In [ ]:
#Nested if else statement Example
a <- 10
b <- 11


if(a == 10)
{
  if(b == 10)
  {
    print("a:10 b:10")
  } else
  {
    print("a:10 b:11")
  }
} else
{
  if(a == 11)
  {
    print("a:11 b:10")
  } else
  {
    print("a:11 b:11")
  }
}

[1] "a:10 b:11"


### Switch

In [ ]:
val1 = 6
val2 = 7
val3 = "s"
result = switch(
  val3,
  "a"= cat("Addition =", val1 + val2),
  "d"= cat("Subtraction =", val1 - val2),
  "r"= cat("Division = ", val1 / val2),
  "s"= cat("Multiplication =", val1 * val2),
  "m"= cat("Modulus =", val1 %% val2),
  "p"= cat("Power =", val1 ^ val2)
)
print(result)

Multiplication = 42NULL


## Loops

### For loop

In [ ]:
#1)

week <- c('Sunday',
          'Monday',
          'Tuesday',
          'Wednesday',
          'Thursday',
          'Friday',
          'Saturday')

# using for loop to iterate over each string in the vector
for (day in week)
{
  print(day)
}

[1] "Sunday"
[1] "Monday"
[1] "Tuesday"
[1] "Wednesday"
[1] "Thursday"
[1] "Friday"
[1] "Saturday"


In [ ]:
#2)

my_list <- list(1, 2, 3, 4, 5)

# Loop through the list and print each element
for (i in seq_along(my_list)) {
  current_element <- my_list[[i]]
  print(paste("The current element is:", current_element))
}

[1] "The current element is: 1"
[1] "The current element is: 2"
[1] "The current element is: 3"
[1] "The current element is: 4"
[1] "The current element is: 5"


### While loop

In [ ]:
val = 1
while (val <= 5)
{
  print(val)
  val = val + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


### repeat loop

In [ ]:
val = 1
repeat
{
  print(val)
  val = val + 1

  # checking stop condition
  if(val > 5)
  {
    break
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


### Jump Statments in loops

#### 1. break

In [ ]:
for (val in 1: 5)
{
  if (val == 3)
  {
    break
  }

  print(val)
}

[1] 1
[1] 2


#### 2. next

In [ ]:
for (val in 1: 5)
{
  if (val == 3)
  {
    next
  }

  print(val)
}

[1] 1
[1] 2
[1] 4
[1] 5


## Functions

In [ ]:
add_num <- function(a,b)
  {
    sum_result <- a+b
    return(sum_result)
  }
  sum = add_num(35,34)
  print(sum)

[1] 69


## Dataframe Manipulation

### 1. Row selection

In [ ]:
df = data.frame(
    "Name" = c("Amiya", "Raj", "Asish"),
    "Language" = c("R", "Python", "Java"),
    "Age" = c(22, 25, 45))
print(df)
  # Accessing first and second row
cat("Accessing first and second row\n")
print(df[1:2, ])

   Name Language Age
1 Amiya        R  22
2   Raj   Python  25
3 Asish     Java  45
Accessing first and second row
   Name Language Age
1 Amiya        R  22
2   Raj   Python  25


### 2. Column selection

In [ ]:
df = data.frame(
  "Name" = c("Amiya", "Raj", "Asish"),
  "Language" = c("R", "Python", "Java"),
  "Age" = c(22, 25, 45))
print(df)
# Accessing first and second row
cat("Accessing first and second row\n")
print(df[,1:2])

   Name Language Age
1 Amiya        R  22
2   Raj   Python  25
3 Asish     Java  45
Accessing first and second row
   Name Language
1 Amiya        R
2   Raj   Python
3 Asish     Java


### 3. Editing

In [ ]:
df = data.frame(
  "Name" = c("Amiya", "Raj", "Asish"),
  "Language" = c("R", "Python", "Java"),
  "Age" = c(22, 25, 45)
)
print(df)

df[[3]][3] = 30

cat("After edited the dataframe\n")
print(df)

   Name Language Age
1 Amiya        R  22
2   Raj   Python  25
3 Asish     Java  45
After edited the dataframe
   Name Language Age
1 Amiya        R  22
2   Raj   Python  25
3 Asish     Java  30


### 4. Adding a row

In [ ]:
df = data.frame(
  "Name" = c("Amiya", "Raj", "Asish"),
  "Language" = c("R", "Python", "Java"),
  "Age" = c(22, 25, 45)
)
cat("Before adding row\n")
print(df)

# Add a new row using rbind()
newDf = rbind(df, data.frame(Name = "Sandeep",
                             Language = "C",
                             Age = 23
))
cat("After Added a row\n")
print(newDf)

Before adding row
   Name Language Age
1 Amiya        R  22
2   Raj   Python  25
3 Asish     Java  45
After Added a row
     Name Language Age
1   Amiya        R  22
2     Raj   Python  25
3   Asish     Java  45
4 Sandeep        C  23


### 5. Column renaming

In [ ]:
df<-data.frame(col1 = 0:2, col2 = 3:5, col3 = 6:8)
print("Original Data Frame")
print(df)
print("Modified Data Frame")
names(df)[names(df)=="row3"] <-"three"
print(df)

[1] "Original Data Frame"
  col1 col2 col3
1    0    3    6
2    1    4    7
3    2    5    8
[1] "Modified Data Frame"
  col1 col2 col3
1    0    3    6
2    1    4    7
3    2    5    8


### 6. Adding columns

In [ ]:
df<-data.frame(col1 = 0:2, col2 = 3:5, col3 = 6:8)
print ("Original Data Frame")
print (df)

df$"col4"<-0
df$"col5"<-NA
df[["col5"]] <- df[["col1"]] + df[["col2"]]
print ("Modified Data Frame")
print (df)

[1] "Original Data Frame"
  col1 col2 col3
1    0    3    6
2    1    4    7
3    2    5    8
[1] "Modified Data Frame"
  col1 col2 col3 col4 col5
1    0    3    6    0    3
2    1    4    7    0    5
3    2    5    8    0    7


### 7. Removing columns

In [ ]:
df<-data.frame(col1 = 0:2, col2 = 3:5, col3 = 6:8)
print ("Original Data Frame")
print (df)
df[["col2"]]<-NULL
print(df)

#by index:
df<-data.frame(col1 = 0:2, col2 = 3:5, col3 = 6:8)
print ("Original Data Frame")
print (df)
#removing two columns
df <- df [-c(1, 3)]
print(df)

[1] "Original Data Frame"
  col1 col2 col3
1    0    3    6
2    1    4    7
3    2    5    8
  col1 col3
1    0    6
2    1    7
3    2    8
[1] "Original Data Frame"
  col1 col2 col3
1    0    3    6
2    1    4    7
3    2    5    8
  col2
1    3
2    4
3    5


### 8. Subsetting dataframe

In [ ]:
df<-data.frame(col1 = 0:2, col2 = 3:5, col3 = 6:8)
print ("Original Data Frame")
print (df)

df<-subset(df, select = - c(col1, col2))
print("Modified Data Frame")
print(df)

[1] "Original Data Frame"
  col1 col2 col3
1    0    3    6
2    1    4    7
3    2    5    8
[1] "Modified Data Frame"
  col3
1    6
2    7
3    8


### 9. Deleting rows and colummns:

In [ ]:
df = data.frame(
  "Name" = c("Amiya", "Raj", "Asish"),
  "Language" = c("R", "Python", "Java"),
  "Age" = c(22, 25, 45))
cat("Before deleting the 3rd row and 2nd column\n")
print(df)
newDF = df[-3, -2]
cat("After Deleted the 3rd row and 2nd column\n")
print(newDF)

Before deleting the 3rd row and 2nd column
   Name Language Age
1 Amiya        R  22
2   Raj   Python  25
3 Asish     Java  45
After Deleted the 3rd row and 2nd column
   Name Age
1 Amiya  22
2   Raj  25


## Reading CSV files

In [ ]:
myData = read.csv("basic.csv")
print(myData)

   Name Age Occupation          City
1  John  23   Engineer      New York
2 Alice  30     Doctor   Los Angeles
3   Bob  45     Artist       Chicago
4 Emily  25  Scientist San Francisco
